WITH
  COMPLETENESS_RF_FLOW AS (
  SELECT
    DT_OPERACAO,
    COUNT(*) AS REGS_FLOW_COMPLETENESS
  FROM
    `nu-br-data.dataset.ready_nu_invest_flow_rf`
  WHERE
        DT_OPERACAO IS NULL OR  ACCOUNTNUMBER IS NULL OR NUM_TITULO IS NULL OR CD_BOLETA IS NULL 
  GROUP BY
    1)
    SELECT
  A.DT_OPERACAO,
  REGS_FLOW_COMPLETENESS 
FROM
  COMPLETENESS_RF_FLOW A
 
WHERE
  A.REGS_FLOW_COMPLETENESS <> 0  
ORDER BY
  dt_operacao 
